### ISSUE TITLE
Capabilites of the MacOS VM

### ISSUE THREAD

**Issue by mur1chan** [MatthewCroughan/NixThePlanet#10]
Hello,

First of all I wanted to thank you for this great project! I appreciate all the work you have put in.

I wanted to ask if it is possible to allow the MacOS VM Ethernet. After I let the setup run everything I couldn't access the internet. And my other question is if it is possible to change the CPU Cores, Threads etc.

Thanks in advance!!

**Comment by MatthewCroughan** [comment]
All of this should be explained already in the readme. You can pass qemu flags directly in the CLI. Read the readme.
