### ISSUE TITLE
android emulator support?

### ISSUE THREAD

**Issue by patryk4815** [MatthewCroughan/NixThePlanet#18]
Maybe add android emulator support 🤔  Didn't find any flake for it.

**Comment by io12** [comment]
I think nixpkgs can do this https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/android.section.md#spawning-emulator-instances-spawning-emulator-instances. There is also Waydroid.

**Comment by patryk4815** [comment]
@io12 it works, xd Thanks

**Comment by MatthewCroughan** [comment]
Yeah, that already exists in Nixpkgs. Closing.
