### ISSUE TITLE
MacOS browser renders page then goes blank

### ISSUE THREAD

**Issue by ajlennon** [MatthewCroughan/NixThePlanet#27]
Trying to run Safari in the MacOS Nix Hackintosh.

It renders a page then immediately goes blank like this.

![image](https://github.com/MatthewCroughan/NixThePlanet/assets/1537834/6f3a8aca-4683-426c-bcc5-2baaba7cbad9)

**Comment by ajlennon** [comment]
Been trying to install Chrome but without a working browser it's a problem. Do you happen to know what the command line looks like to do this?

**Comment by MatthewCroughan** [comment]
Yeah I think this applies still https://superuser.com/questions/602680/how-to-install-google-chrome-from-the-command-line

I've wanted to do declarative things and develop my code further to allow you to do things like `makeDarwinImage { installChrome = true; }`, which would declaratively do this, but haven't had the time.

**Comment by ajlennon** [comment]
I managed to get it installed by running up a terminal and switching between the safari browser and the terminal as when the terminal shows the browser pane magically comes back for a second
