### ISSUE TITLE
403 when trying to download image

### ISSUE THREAD

**Issue by colonelpanic8** [MatthewCroughan/NixThePlanet#34]
Getting

 error: unable to download 'https://swcdn.apple.com/content/downloads/46/31/052-96247-A_MLN9N00Y8W/dmml3up52hrsb01krjtczmdhexiruv1b5m/InstallAssistant.pkg': HTTP error 403
 
 Has anyone else seen this?

**Comment by MatthewCroughan** [comment]
Yeah, Apple deletes the image from time to time, so we have to get the latest, or find the old one somewhere archived on the internet where we can fetch it.

**Comment by MatthewCroughan** [comment]
Actually, looks like this isn't the case this time. If you're experiencing a 403, that means Apple is forbidding you personally based on some criteria. Perhaps due to your network.

**Comment by aciceri** [comment]
Done! You have to trigger Hercules somehow?

**Comment by MatthewCroughan** [comment]
@aciceri the HCI build is triggered be me pulling and pushing your branch like this:

- `git fetch origin pull/36/head:pr-36-ci`
- `git push origin pr-36-ci`

The build is ongoing here https://hercules-ci.com/github/MatthewCroughan/NixThePlanet/jobs/487
