### ISSUE TITLE
Viewing darwin image build progress or verifying QEMU performance

### ISSUE THREAD

**Issue by thoelze1** [MatthewCroughan/NixThePlanet#38]
Running `nix run github:matthewcroughan/NixThePlanet#macos-ventura` takes more than two hours, even after all the downloading has finished. I want to make sure that nothing has gone wrong, so I am looking for a way to view the graphical install progress or for a way to verify the performance of QEMU. I tried using a VNC client to view the graphical install, but I am unable to connect to the passed address:port. Is it possible to view the graphical install with a VNC client and, if so, how do I properly pass the -vnc flag? Is there another way I can verify that building the darwin image is moving along? Is it normal for CPU to be max'ed out? How can I be certain that KVM and IOMMU are active? Thank you.

**Comment by MatthewCroughan** [comment]
@thoelze1 enable the `impure-derivations` experimental feature, uncomment the `__impure = true` line in https://github.com/MatthewCroughan/NixThePlanet/blob/ef5fad336a55fcbb0680ad21aa58812b2f826435/makeDarwinImage/default.nix#L240

Then connect to the host on port 5901 with a VNC viewer.

The install process does take more than two hours. If you have a PR you can make, or insights on how to improve that, then please do! I would love to improve it.

**Comment by MatthewCroughan** [comment]
> How can I be certain that KVM and IOMMU are active? 

That has nothing to do with this repo, yet. Though I have played around with the idea of supporting things like GPU passthrough via VFIO in the nixosModules. At the moment, this to do with your personal configuration, hardware, etc. Maybe we should write a wiki.nixos.org page about this, but there are plenty of resources to find out more about this with a search. E.g https://astrid.tech/2022/09/22/0/nixos-gpu-vfio/
