### ISSUE TITLE
How do you increase `diskSize` ?

### ISSUE THREAD

**Issue by fillon** [MatthewCroughan/NixThePlanet#6]
Hi

Great project... loving it

Installed macos and trying to install Xcode and ran out of space (50GB)

How do you setup a bigger diskSize?

**Comment by MatthewCroughan** [comment]
It is [documented in the README.md how to use the `makeDarwinImage` function](https://github.com/MatthewCroughan/NixThePlanet#using-the-makedarwinimage-function), and there is a `package` option for the `macos-ventura` module. So if you're familiar with NixOS you should be able to figure out how to use this to set the disk size.

```
services.macos-ventura = {
  enable = true;
  package = pkgs.makeDarwinImage { diskSizeBytes = 60000000000; };
};
```

This will incur a full rebuild of the base disk image. I would like to figure out a way of expanding this that doesn't involve a full rebuild of the disk image, by creating a second image that will `ssh` into the VM and perform resize operations. I will implement this in the future.

**Comment by fillon** [comment]
Thanks :) I was trying to figure out what I was doing wrong.

Down the track, how would you a force rebuild of the vm? I could not find where the ./macos-ventura.qcow2 is located.
Lost of black magic, just 3 months into nix so still in learning phase. But greatly impressed by the possibilities.

**Comment by MatthewCroughan** [comment]
There's no black magic here, it just puts the qcow2 image into the `dataDir` option which defaults to `/var/lib/nixtheplanet-macos-ventura`

https://github.com/MatthewCroughan/NixThePlanet/blob/2dec745defe105e94397f713d4d4ad7caf488884/makeDarwinImage/module.nix#L16-L19

**Comment by fillon** [comment]
that's what i have . no qcow2 file there
```
ls -als /var/lib/nixtheplanet-macos-ventura 
 /var/lib/nixtheplanet-macos-ventura -> private/nixtheplanet-macos-ventura
```

**Comment by MatthewCroughan** [comment]
It's a symlink to `private/nixtheplanet-macos-ventura` which you're not looking in.

**Comment by fillon** [comment]
got it.. feeling dumb now

**Comment by MatthewCroughan** [comment]
No problem, it can be confusing. The reason it's a symlink into `private` is because of the systemd DynamicUser option

https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#DynamicUser=

This means the VM is launched in QEMU with a random UID every single time, and systemd chowns the file to the QEMU process each time the service is launched.

**Comment by rastarr** [comment]
> It's a symlink to `private/nixtheplanet-macos-ventura` which you're not looking in.

How do I go about removing trace of this VM including the created stuff in private/nixtheplanet-macos-ventura ?

**Comment by MatthewCroughan** [comment]
@rastarr 

```
rm -rf  /var/lib/nixtheplanet-macos-ventura
rm -rf /var/lib/private/nixtheplanet-macos-ventura
nix-collect-garbage
```
